#!/usr/bin/env python3
"""
Verifies a gap in Topic 1's O(2^n) derivation that was never checked
before this sweep: the formula 2^(n_ext-1) - n_ext - 1 counts abstract
non-trivial bipartitions of the n_ext external legs, but never confirmed
that every such bipartition is actually REALIZABLE as an internal line
of some cubic (trivalent) tree topology on those legs -- as opposed to
being a bipartition that no valid tree diagram could ever produce.

Enumerates every cubic tree topology on 5 labeled external legs
(n=3, our worked example) by recursive pairwise merging, collects every
bipartition realized by some internal line of some topology, and checks
it against the formula's counted set exactly.
"""
from itertools import combinations


def all_cubic_tree_topologies(external_legs):
    """Yields the set of internal-line bipartitions for every distinct
    cubic tree topology on the given external legs (generated by
    recursively merging pairs of legs into internal vertices)."""
    if len(external_legs) == 2:
        yield set()
        return
    for i, j in combinations(range(len(external_legs)), 2):
        a, b = external_legs[i], external_legs[j]
        rest = [x for k, x in enumerate(external_legs) if k not in (i, j)]
        a_set = a if isinstance(a, frozenset) else frozenset([a])
        b_set = b if isinstance(b, frozenset) else frozenset([b])
        merged = a_set | b_set
        new_legs = rest + [merged]
        for sub_bip in all_cubic_tree_topologies(new_legs):
            yield sub_bip | {merged}


def canonical(s, full):
    comp = full - s
    return min(s, comp, key=lambda x: sorted(x))


all_legs = [0, 1, 2, 3, 4]
n_ext = len(all_legs)
full = frozenset(all_legs)

achievable = set()
for bip in all_cubic_tree_topologies(all_legs):
    for s in bip:
        if len(s) in (0, 1, n_ext - 1, n_ext):
            continue  # trivial: empty/full (overall conservation) or single-leg (external, not internal)
        achievable.add(canonical(s, full))

formula_set = set()
for size in range(2, n_ext - 1):
    for combo in combinations(all_legs, size):
        formula_set.add(canonical(frozenset(combo), full))

print(f"n_ext={n_ext}: achievable bipartitions (from real cubic tree topologies): {len(achievable)}")
print(f"n_ext={n_ext}: formula-counted bipartitions (2^(n_ext-1)-n_ext-1): {len(formula_set)}")
print(f"achievable == formula_set: {achievable == formula_set}")
assert achievable == formula_set, "formula counts a bipartition no tree topology can realize, or vice versa"
print("Confirmed: every bipartition the formula counts is realized by some actual")
print("cubic tree topology, and no achievable bipartition is missed by the formula.")
